# Generated by Django 3.2.3 on 2021-07-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('director', models.CharField(max_length=50, verbose_name='Director')),
                ('content', models.TextField(verbose_name='Content')),
                ('value', models.CharField(max_length=150, verbose_name='Value')),
            ],
        ),
    ]
