# Generated by Django 3.2.3 on 2021-07-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210721_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='mylist',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
