# Generated by Django 3.2.3 on 2021-07-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210721_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylist',
            name='value',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Value'),
        ),
    ]
